# Generated by Django 4.2.7 on 2023-11-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tasklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
